# Generated by Django 3.1.3 on 2020-11-11 11:01

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="AwaitingData",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("guid", models.UUIDField(default=uuid.uuid4)),
                ("type", models.CharField(max_length=20)),
                ("key", models.CharField(max_length=100)),
                ("value", models.CharField(max_length=100)),
                ("date", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "unique_together": {("guid", "type", "key")},
            },
        ),
    ]
