# Generated by Django 3.1.3 on 2020-11-27 15:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_friends"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="friends",
            unique_together={("user", "friend")},
        ),
    ]
